#!/bin/bash

CURRENT_DIR="$(dirname "$0")"

# Creating a test pack using st2sdk
st2sdk bootstrap test_pack
cd test_pack

# Registering dummy remote repository to pass the verification check
git init
git remote add origin git@github.com:StackStorm/st2sdk.git
git fetch origin

# Checking the created pack is valid as with other stackstorm-exchange's one
ROOT_DIR="${CURRENT_DIR}/test_pack" FORCE_CHECK_ALL_FILES=true ~/ci/.circle/test
